output_path : /mnt/temp/projects/otago_uni_marsden/data_keep/spg/training_params/daily/
input_path : /mnt/temp/projects/otago_uni_marsden/data_keep/spg/station_data/
ens_path : /mnt/temp/projects/otago_uni_marsden/data_keep/spg/ensemble_daily/

num_ens : 10
num_valid : 1000

train_func: train_obs
train_kwargs : 
  freq : 24H

max_values :
  dunedin : 220
  dunedin_combined : 220
  dunedin_aero : 220  
  tarahills : 200
  tauranga : 400
  christchurch : 180
  auckland : 250


scenarios :
  - rcp85
  - ssp585
  - rcp26
  - rcp45
  - rcp60
  - ssp119
  - ssp126
  - ssp245
  - ssp370
  - ssp434
  - ssp460
  